
GET http://localhost:4000/loan
###
POST http://localhost:4000/loan/calculate
Content-Type: application/json

{
  "loanAmount": 560000,
  "interestRate": 3.5,
  "repaymentPeriodYears": 50
}


###
GET http://localhost:5215/todos/2

###
DELETE http://localhost:5215/todos/2

###
GET http://localhost:5215/tasks/1





